//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_platformer p_platformer;
        
        private static SteamVR_Input_ActionSet_buggy p_buggy;
        
        private static SteamVR_Input_ActionSet_joystickmotion p_joystickmotion;
        
        private static SteamVR_Input_ActionSet_snapturn p_snapturn;
        
        private static SteamVR_Input_ActionSet_joystickteleporthybrid p_joystickteleporthybrid;
        
        private static SteamVR_Input_ActionSet_handdirectedsteering p_handdirectedsteering;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_platformer platformer
        {
            get
            {
                return SteamVR_Actions.p_platformer.GetCopy<SteamVR_Input_ActionSet_platformer>();
            }
        }
        
        public static SteamVR_Input_ActionSet_buggy buggy
        {
            get
            {
                return SteamVR_Actions.p_buggy.GetCopy<SteamVR_Input_ActionSet_buggy>();
            }
        }
        
        public static SteamVR_Input_ActionSet_joystickmotion joystickmotion
        {
            get
            {
                return SteamVR_Actions.p_joystickmotion.GetCopy<SteamVR_Input_ActionSet_joystickmotion>();
            }
        }
        
        public static SteamVR_Input_ActionSet_snapturn snapturn
        {
            get
            {
                return SteamVR_Actions.p_snapturn.GetCopy<SteamVR_Input_ActionSet_snapturn>();
            }
        }
        
        public static SteamVR_Input_ActionSet_joystickteleporthybrid joystickteleporthybrid
        {
            get
            {
                return SteamVR_Actions.p_joystickteleporthybrid.GetCopy<SteamVR_Input_ActionSet_joystickteleporthybrid>();
            }
        }
        
        public static SteamVR_Input_ActionSet_handdirectedsteering handdirectedsteering
        {
            get
            {
                return SteamVR_Actions.p_handdirectedsteering.GetCopy<SteamVR_Input_ActionSet_handdirectedsteering>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_platformer = ((SteamVR_Input_ActionSet_platformer)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_platformer>("/actions/platformer")));
            SteamVR_Actions.p_buggy = ((SteamVR_Input_ActionSet_buggy)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_buggy>("/actions/buggy")));
            SteamVR_Actions.p_joystickmotion = ((SteamVR_Input_ActionSet_joystickmotion)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_joystickmotion>("/actions/joystickmotion")));
            SteamVR_Actions.p_snapturn = ((SteamVR_Input_ActionSet_snapturn)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_snapturn>("/actions/snapturn")));
            SteamVR_Actions.p_joystickteleporthybrid = ((SteamVR_Input_ActionSet_joystickteleporthybrid)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_joystickteleporthybrid>("/actions/joystickteleporthybrid")));
            SteamVR_Actions.p_handdirectedsteering = ((SteamVR_Input_ActionSet_handdirectedsteering)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_handdirectedsteering>("/actions/handdirectedsteering")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.platformer,
                    SteamVR_Actions.buggy,
                    SteamVR_Actions.joystickmotion,
                    SteamVR_Actions.snapturn,
                    SteamVR_Actions.joystickteleporthybrid,
                    SteamVR_Actions.handdirectedsteering};
        }
    }
}
